name: Android CI - Studio Modern

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Fix gradlew line endings
      run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

    - name: Clean build & assembleDebug
      run: ./gradlew clean assembleDebug

    - name: Upload APK (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: SerikatPekerjaApp-debug
        path: app/build/outputs/apk/debug/app-debug.apk
