name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Fix gradlew line endings (Unix LF)
      run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Clean Gradle build
      run: ./gradlew clean

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: serikatpekerja-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
